let text = "defend the east wall of the castle";

let result = text
.replaceAll("a","1")
.replaceAll("b","2")
.replaceAll("c","3")
.replaceAll("d","4")
.replaceAll("e","5")
.replaceAll("f","6")
.replaceAll("g","7")
.replaceAll("h","8")
.replaceAll("i","9")
.replaceAll("j","10")
.replaceAll("k","11")
.replaceAll("l","12")
.replaceAll("m","13")
.replaceAll("n","14")
.replaceAll("o","15")
.replaceAll("p","16")
.replaceAll("q","17")
.replaceAll("r","18")
.replaceAll("s","19")
.replaceAll("t","20")
.replaceAll("u","21")
.replaceAll("v","22")
.replaceAll("w","23")
.replaceAll("x","24")
.replaceAll("y","25")
.replaceAll("z","26")

.replaceAll("1","b")
.replaceAll("2","c")
.replaceAll("3","d")
.replaceAll("4","e")
.replaceAll("5","f")
.replaceAll("6","g")
.replaceAll("7","h")
.replaceAll("8","i")
.replaceAll("9","j")
.replaceAll("10","k")
.replaceAll("11","l")
.replaceAll("12","m")
.replaceAll("13","n")
.replaceAll("14","o")
.replaceAll("15","p")
.replaceAll("16","q")
.replaceAll("17","r")
.replaceAll("18","s")
.replaceAll("19","t")
.replaceAll("20","u")
.replaceAll("21","v")
.replaceAll("22","w")
.replaceAll("23","x")
.replaceAll("24","y")
.replaceAll("25","z")
.replaceAll("26","a");

console.log(result);